[package]
name = "wasm-fiddler"
version = "0.0.0"
authors = ["Da BOXEN"]
description = "Some silly goofy"
license = "All Rights Reserved"
repository = "https://github.com/yourgithubusername/hello-wasm"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"